### ISSUE TITLE
Does it work with polycam models?

### ISSUE THREAD

**Issue by karen-pal** [dylanebert/gsplat.js#15]
Hello! Thank you for your work, it looks very promising. Got it working with the README file... Just tried it with a .ply object out of polycam and got error

```
Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at R.setData (Scene.ts:43:25)
    at W.LoadAsync (Loader.ts:31:15)
    at async main (main.ts:11:5)

```

with what file type is it compatible? Thanks!

**Comment by dylanebert** [comment]
Are you using SPLAT.PlyLoader? You can see an example of converting .ply to .splat here: https://github.com/dylanebert/gsplat.js/blob/main/examples/ply-converter/src/main.ts

**Comment by dylanebert** [comment]
Sure, here is an example loading and converting a PLY file from URL: [jsfiddle](https://jsfiddle.net/d8ebst19/5/)
