### ISSUE TITLE
Ubuntu problems.

### ISSUE THREAD

**Issue by graemeniedermayer** [dylanebert/gsplat.js#19]
It doesn't seem to work on Ubuntu. Does this require any newer chrome features? Dev tools don't give any errors just a flickering black box. It does seem to be using lots of resources so maybe it's a bottleneck.

This also might be a me problem.

This implementation works amazing on android. Fast! Thanks you!

**Comment by dylanebert** [comment]
Thanks! Is the issue on the online demo or your local project? And which web browser?

**Comment by graemeniedermayer** [comment]
I thought I was using chrome, just realised I was using chromium. Checked it with chrome and firefox both work so I think I'll close this issue! 

Thanks.
