### ISSUE TITLE
About the  automatic rotation display feature

### ISSUE THREAD

**Issue by spark323** [dylanebert/gsplat.js#32]
Originally, the [PR ](https://github.com/dylanebert/gsplat.js/pull/29) was part of my implementation for the automatic rotation feature (example: [url ](https://mini.rubywave.io/)). And I am currently preparing another PR for this specific feature.

(FYI, it not only changes the Alpha value but also slightly adjusts the Beta value over time to cover the entire area in view.)

However, I'm wondering if this is something that gsplat should provide as a built-in feature or if it's something that people should implement on their own using functions exposed by gsplat.

What do you think?

**Comment by jeyemwey** [comment]
I love the idea of having an automatic movement feature, not only for rotation but also to follow the original video movement (that's a feature of the [INRIA implementation](https://github.com/graphdeco-inria/gaussian-splatting)).
However, I'm not sure if we should add those functions to the library or keep them external and just create a `FollowCameraTrackControls` class.

To make it approachable for beginners, I'd still like to have your code in an example maybe? Or in a dedicated documentation (tho I don't know of plans if/how that would be planned).

**Comment by dylanebert** [comment]
I think it's a good idea to have this as an example rather than a built-in feature. Maybe it could be part of the camera-updates example? The examples could be made for structured and extensive with READMEs as well

**Comment by spark323** [comment]
I didn't understand the reference to the original video movement part you mentioned earlier so I've developed a quick version of  the video movement feature(FollowCameraTrackControls) that follows a predefined path based on my understanding.

For example,In this [example](https://mini.rubywave.io/followcam/), you can press 'startRecord' to move the scene as you desire and then 'stopRecord.' Hit 'playRecord' to replay the camera movement. Internally, it records a track of camera movements and replays them using that recorded data

(Just to let you know, it hasn't been optimized or cleaned up in terms of code quality yet, only tested in Chrome)
