### ISSUE TITLE
About SH data and View dependent appearance 

### ISSUE THREAD

**Issue by prakashknaikade** [dylanebert/gsplat.js#37]
I tried one scene which has view dependent colors, but rendered view dependent colors are not good.
How the SH data handled in gsplat.js?

**Comment by dylanebert** [comment]
There are currently no SH coefficients (except SH0 i.e. color)

**Comment by prakashknaikade** [comment]
Can you please add a functionality of loading all SH coefficients?

**Comment by dylanebert** [comment]
I opened an [issue](https://github.com/dylanebert/gsplat.js/issues/38) for it
